import Head from "next/head";
import Banner from "../src/components/Banner";
import FeaturedProducts from "../src/components/FeaturedProducts";
import UpcomingAuctions from "../src/components/UpcomingAuctions";
import TopCreators from "../src/components/TopCreators";
import MainLayout from "../src/layouts/MainLayout";

export default function Home({ banner, featuredData, upcomingData }) {
  return (
    <>
      <Head>
        <title>Artsy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Banner data={banner} />
        <FeaturedProducts data={featuredData} />
        <UpcomingAuctions data={upcomingData} />
        <TopCreators />
      </MainLayout>
    </>
  );
}

export async function getServerSideProps() {
  const { banner_info, featured, upcoming } = await import("../data/data.json");
  return {
    props: {
      banner: banner_info,
      featuredData: featured,
      upcomingData: upcoming,
    },
  };
}
